server:
  port: 8080

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:aws-wrapper:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: software.amazon.jdbc.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      max-lifetime: 840000

      data-source-properties:
        wrapperPlugins: iam
        iamRegion: ${AWS_REGION}

  jpa:
    hibernate:
      ddl-auto: validate   # ❗ DO NOT use update in prod
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

logging:
  level:
    root: INFO
    com.Deye: INFO